version: '3.9'

services:
  fastapi:
    container_name: film_search
    image: film_search:v1.0
    build: .
    env_file:
      - ./envs/.fastapi.env
    ports:
      - 8000:8000
    depends_on:
      - es
      - redis
  es:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - discovery.type=single-node
    restart: always
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
volumes:
  elastic_data:
